apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort
  selector:
    app: posts
  ports:
    - name: posts # for logging
      protocol: TCP
      port: 4000 # facing side
      targetPort: 4000 # internal to the pod
