apiVersion: apps/v1
kind: Deployment
metadata:
  name: query
spec:
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: adrianrosario/query
          resources:
            # limits:
            #   memory: "128Mi"
            #   cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: query-cluster-ip-service
spec:
  selector:
    app: query
  ports:
    - name: query-cluster-ip-service
      protocol: TCP
      port: 4002
      targetPort: 4002
