apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: us.gcr.io/fourth-carport-417818/tickets
          env:
            - name: MONGO_URI
              value: "mongodb://tickets-mongodb-cluster-ip-service:27017/tickets"
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv-cluster-ip-service
spec:
  selector:
    app: tickets
  ports:
    - name: tickets-cluster-ip-service
      protocol: TCP
      port: 3000
      targetPort: 3000
