apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
spec:
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: adrianrosario/comments
          resources:
            # limits:
            #   memory: "128Mi"
            #   cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: comments-cluster-ip-service
spec:
  selector:
    app: comments
  ports:
    - name: comments-cluster-ip-service
      protocol: TCP
      port: 4001
      targetPort: 4001
