apiVersion: skaffold/v2alpha3
kind: Config
build:
  # local:
  # push: true # false
  googleCloudBuild:
    projectId: fourth-carport-417818
  artifacts:
    - image: us.gcr.io/fourth-carport-417818/auth # adrianrosario/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: us.gcr.io/fourth-carport-417818/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: us.gcr.io/fourth-carport-417818/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: us.gcr.io/fourth-carport-417818/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
